# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: 19D070026@iitb.ac.in
  description: Hello everyone. I am Jay Sonawane, an electrical engineering freshmen. I have interests in robotics, control theory, differential equations. If you want to catch up working on a project with me then feel free to contact.
baseurl: "/hyperspace-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://github.com/jayson-310801/" # the base hostname & protocol for your site

# Social settings
500px_url: 
facebook_url: https://facebook.com
github_url: https://github.com/jayson-310801/
gitlab_url: 
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
